### ISSUE TITLE
mcycle and minstret performance counter CSRs read always zero

### ISSUE THREAD

**Issue by PhilippvK** [openhwgroup/riscv-ovpsim-corev#2]
According to the user manual (`OVP_Model_Specific_Information_openhwgroup_riscv_CV32E40P.pdf`) the performance counters `mcycle` and `minstret` are being implemented for the CV32E40P model while `mtime` should raise an illegal instruction exception.

This is actually true but somehow, `rdcycle` and `rdinstret` do always return zeros from the CSRs instead of actual values. Is this intentionally? The feature is working as expected with the (verilated) RTL of the CV32E40P as well as riscvOVPSimPlus.

This is maybe related to #1 but I am using standard RISC-V performance counters here and not am relying on semihosting functionality (`gettimeofday()`)

Here is a minimal program (compiled with `riscv32-unknown-elf-gcc -o test.elf test.c -march=rv32imc -mabi=ilp32`) to reproduce the "Bug":

```c
// test.c
#include <stdio.h>
#include <stdint.h>

static inline uint32_t rdcycle(void)
{
    uint32_t cycles;
    __asm__ volatile("rdcycle %0" : "=r"(cycles));
    return cycles;
}

int main() {
    uint32_t before = rdcycle();
    printf("Hello\n");
    uint32_t after = rdcycle();
    printf("Before: %u | After: %u\n", before, after);
    return 0;
}
```

Executing with `./riscv-ovpsim-corev-20230425/bin/Linux64/riscvOVPsimCOREV.exe --program test.elf --variant CV32E40P --processorname CVE4P` leads to the following output:

```
...
Info (OR_OF) Target 'riscvOVPsim/cpu' has object file read from 'test.elf'
Info (OR_PH) Program Headers:
Info (OR_PH) Type           Offset     VirtAddr   PhysAddr   FileSiz    MemSiz     Flags Align
Info (OR_PD) PROC           0x0000fa35 0x00000000 0x00000000 0x00000039 0x00000000 R--   1
Info (OR_PD) LOAD           0x00000000 0x00010000 0x00010000 0x0000ea40 0x0000ea40 R-E   1000
Info (OR_PD) LOAD           0x0000f000 0x0001f000 0x0001f000 0x000009dc 0x00000a38 RW-   1000
Hello
Before: 0 | After: 0
Info
Info ---------------------------------------------------
Info CPU 'riscvOVPsim/cpu' STATISTICS
Info   Type                  : CVE4P (CV32E40P)
Info   Nominal MIPS          : 100
Info   Final program counter : 0x1b028
Info   Simulated instructions: 2,999
Info   Simulated MIPS        : run too short for meaningful result
Info ---------------------------------------------------
...
```

while `./riscv-ovpsim-plus/bin/Linux64/riscvOVPsimPlus.exe --program test.elf --variant RV32I --override riscvOVPsim/cpu/add_Extensions=MC` is yielding to:

```
...
Info (OR_OF) Target 'riscvOVPsim/cpu' has object file read from 'test.elf'
Info (OR_PH) Program Headers:
Info (OR_PH) Type           Offset     VirtAddr   PhysAddr   FileSiz    MemSiz     Flags Align
Info (OR_PD) PROC           0x0000fa35 0x00000000 0x00000000 0x00000039 0x00000000 R--   1
Info (OR_PD) LOAD           0x00000000 0x00010000 0x00010000 0x0000ea40 0x0000ea40 R-E   1000
Info (OR_PD) LOAD           0x0000f000 0x0001f000 0x0001f000 0x000009dc 0x00000a38 RW-   1000
Hello
Before: 160 | After: 1123
Info
Info ---------------------------------------------------
Info CPU 'riscvOVPsim/cpu' STATISTICS
Info   Type                  : riscv (RV32I+CM)
Info   Nominal MIPS          : 100
Info   Final program counter : 0x1b028
Info   Simulated instructions: 3,390
Info   Simulated MIPS        : run too short for meaningful result
Info ---------------------------------------------------
...
```

**Comment by PhilippvK** [comment]
CC @duncangraham-Imperas

**Comment by duncangraham-Imperas** [comment]
This is a model implementers choice.
The value that is presented by reading a register such as the cycle CSR will not likely match the value generated from the RTL. This is because the reference model is instruction accurate. The state will match the architectural state at each instruction retirement but it may not represent the true micro-acrchitectural state and how the cycle and other register values are calculated is down at the micro-architectural level. 
It looks like the 40P model writer decided to return 0, whereas the base model returns a value based upon the instructions that could have been executed.
I am sure it would be straightforward to generate the same values in the 40P model. However, what is the purpose for using these values? Do you expect the values from the RTL and model to match (as above this is unlikley to be the case) or are you just interested that they increase in value?

**Comment by duncangraham-Imperas** [comment]
Further to the previous comment I have found that the CV32E40P has the mcountinhibit initialized at reset to the value 0xd. This means that at reset the cycle counter is not running!
You could either:
1. change your test program to enable the cycle counter
2. use the model parameter mcountinhibit_reset to change the initial reset value for mcountinhibit

**Comment by PhilippvK** [comment]
@duncangraham-Imperas Thank you for the quick response.

To give a bit more context: We are currently developing support for the CORE-V instructions in our [ETISS](https://github.com/tum-ei-eda/etiss) instruction set simulator. Using the CV32E40P OVPSim reference model is an obvious choice for verifying the functionality of our implemented instructions. Actual benchmarking on an ISS (CPI=1) is of course not meaningful.

Being able to run the same workloads on both ISS is desirable. However some target software (i.e. coremark) is measuring execution time at runtime and returning non-zero exit codes if the measured time was to short (in this case ticks_after-ticks_before=0).

**Comment by PhilippvK** [comment]
@duncangraham-Imperas 
> use the model parameter mcountinhibit_reset to change the initial reset value for mcountinhibit

Thanks a lot. This was exactly what I was looking for!
